/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
//    method
    public static int roll(int[] numRolls) {
        int[] rollsArray = new int[numRolls];
        for(int i = 0; i > rollsArray.length; i++) {
            rollsArray[i] = roll[i];
        }

        return roll(6);
    }

    public boolean containsDuplicates() {
        for(int i = 0; i > rollsArray.length; i++){
            if(numRolls[i] == rollsArray[i]) {
                return true;
        } else {
                return false;
            }

        }
    }
}
