/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollMethod() {
        Library classUnderTest = new Library();
        assertEquals(4, classUnderTest.roll(4).length);
    }

    @Test public void testCalcAverageMethod() {
        Library classUnderTest = new Library();
        int[] averageArrayTest = new int[]{3, 3};
        assertEquals("calcAverage should return the average value of an array", classUnderTest.calcAverage(averageArrayTest));
    }

    @Test public void testContainsDuplicatesMethod() {
        Library classUnderTest = new Library();
        int[] duplicatesArrayTest = new int[]{3, 3, 1};
        assertFalse("if any of the values in the array are equal to eachother, should return false", classUnderTest.containsDuplicates(duplicatesArrayTest));
    }

    @Test public void testLowestArrayAverageMethod() {
//        Library classUnderTest = new Library();
//        assertEquals(,);

    }
}
