/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollMethod() {
        Library classUnderTest = new Library();
        assertEquals(4, classUnderTest.roll(4).length);
    }

    @Test public void testCalcAverageMethod() {
        Library classUnderTest = new Library();
        assertEquals("int", classUnderTest.calcAverage(Library.roll(5)));
    }
}
