/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.nio.file.Path;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testLinterReaderMethod() {
        Path file = new Path("C:\Users\humph\401 - Java Android\javafundamentals\linter\resources\gates.js");
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.testLinterReaderMethod());
    }
}
