/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.nio.file.Path;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testLinterReaderMethod() {
        App classUnderTest = new App();


        assertEquals("no error if line is empty", true, classUnderTest.linterReader());
    }
}
