import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public App() {

    }

    public static void main(String[] args) {
        Path imagePath = FileSystems.getDefault().getPath("assets", "bitmapTestImg.bmp");
        Bitmap bmp = new Bitmap(imagePath);
        bmp.flipVertically();
        bmp.save(FileSystems.getDefault().getPath("assets", "img_after.bmp"));
    }
}

