import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // find image
        Path imagePath = FileSystems.getDefault().getPath("assets", "bitmapTestImg.bmp");
        // read image
        Bitmap bmp = new Bitmap(imagePath);
        // mess with image
        bmp.flipVertically();
        // output image
        bmp.save(FileSystems.getDefault().getPath("assets", "img_after.bmp"));

    }



}
