import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void linterReader(Path incomingFile) {  // path goes in tests
        Charset charset = Charset.forName("US-ASCII");
        // reading file -  reader looks at incomingFile
        try(BufferedReader reader = Files.newBufferedReader(incomingFile, charset)) {
            // then this is looking at it line by line
            String lineBeingRead = "";
            int lineNumber = 0;
            int numberOfErrorsCaught = 0;
            // while there are still lines in this file
            while(lineBeingRead != null) {

                // run conditions to check for errors
                if (!lineBeingRead.contains("if") && !lineBeingRead.contains("else") &&
                        !lineBeingRead.isEmpty() && !lineBeingRead.endsWith(";") &&
                        !lineBeingRead.endsWith("}") && !lineBeingRead.endsWith("{")) {
                    // want error message
                    //Line (number of line) "missing semicolon"
                    System.out.println("Line " + lineNumber + " is missing semicolon.");
                    // for test count # of errors
                    numberOfErrorsCaught++;
                }
                lineNumber++;
                lineBeingRead = reader.readLine();
            }
        } catch (IOException x) {
            System.err.format("IOException: %s%n, x");
        }

    }
}
