import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void linterReader(Path incomingFile) {  // path goes in tests
        Charset charset = Charset.forName("US-ASCII");
        try(BufferedReader reader = Files.newBufferedReader(incomingFile, charset)) {
            String currentLine = "";
            int line = 0;
            while(currentLine != null) {
                if(currentLine.endsWith(";")){
                    // do nothing
                }
                System.out.println("Line " + line + " missing semicolon");
            }
        } catch (IOException e) {
            System.err.format("IOException: %s%n, e");
        }

    }

    public static




}
